### ISSUE TITLE
Invalid API version

### ISSUE THREAD

**Issue by TomGullen** [stripe/stripe-dotnet#1535]
Using: Stripe.net 24.0.2 (latest stable)
API version 2019-02-19 (latest)

![1](https://user-images.githubusercontent.com/998934/53162003-05942300-35c3-11e9-98bb-90077d7f3161.png)

![2](https://user-images.githubusercontent.com/998934/53162035-16449900-35c3-11e9-9b21-10f43f58a7bc.png)

Receiving errors:

```
Stripe.StripeException: Received event with API version 2019-02-11, but Stripe.net 24.0.2 expects API version 2019-02-19. You can disable this exception by passing `throwOnApiVersionMismatch=false` to `Stripe.EventUtility.ParseEvent` or `Stripe.EventUtility.ConstructEvent`, but be wary that objects may be incorrectly deserialized.
   at Stripe.EventUtility.ParseEvent(String json, Boolean throwOnApiVersionMismatch) in /_/src/Stripe.net/Services/Events/EventUtility.cs:line 24
```

Vast majority of our webhook messages are throwing this exception now which is causing problems.  I've contacted Stripe support but they are not being very helpful right now.  Any ideas what is causing this?

**Comment by TomGullen** [comment]
I rolled back the API version on Stripe, and upgraded again and it's now showing this:

![1](https://user-images.githubusercontent.com/998934/53162663-67a15800-35c4-11e9-8265-d5040a73fe6d.png)

Am assuming this is a bug on Stripe's API version upgrade.

**Comment by ob-stripe** [comment]
Hi @TomGullen. According to the first screenshots, your account's default API version was `2019-02-11`. Maybe you upgraded it before `2019-02-19` was released?

It sounds like the situation is resolved now, but feel free to reply if you're observing unexpected behavior from the Stripe.net library.

**Comment by TomGullen** [comment]
Possibly did upgrade before the 2019-02-19 was released.  If this is the case there should be a button in Stripe to either roll back or upgrade to the even newer version as this has caused me some confusion and the help links with Stripe don't address this scenario.

Thanks for quick reply!

**Comment by ob-stripe** [comment]
Ack, thanks. We're aware the API version upgrade process is not as clear as it could be and are looking into possible improvements, so this is useful feedback! I'll pass it along.

**Comment by TomGullen** [comment]
Actually still receiving errors in my logs:

`Stripe.StripeException: Received event with API version 2019-02-11, but Stripe.net 24.0.2 expects API version 2019-02-19. You can disable this exception by passing `throwOnApiVersionMismatch=false` to `Stripe.EventUtility.ParseEvent` or `Stripe.EventUtility.ConstructEvent`, but be wary that objects may be incorrectly deserialized.`

Would webhooks being retried be using older API versions?

I'm a little lost now how best to resolve this if the webhooks are being sent with different versions.  I suppose roll back to an older version for now.

**Comment by remi-stripe** [comment]
Events are generated based on the API version set on the Stripe account at the time of the event creation. They are then never changed. If you update your API version a few minutes after this event is created, it will still be formatted based on the previous API version set on the account.

There is unfortunately no way around this limitation today. This means that you need to upgrade the API version an stripe-dotnet together in your integration and you likely still need a separate logic to handle past events that were not delivered successfully and would be retried.
